### PR TITLE
Adding validity_period variable in etcd_certs module

### PR DESCRIPTION
**Pull request by jass-k**
This is required to update etcd-certs plan when validity period is updated

### CODE REVIEW

**Review by gp2805 — COMMENTED** [review]
👍

**Review by gp2805 — APPROVED** [review]

**Review by ankushvijay93 — APPROVED** [review]
LGTM

**Review by ricardofbarros — APPROVED** [review]
LGTM

**Review by ricardofbarros — APPROVED** [review]
LGTM! Let's have this merged ASAP.

**Pull request merged**
